### PR TITLE
Single Number problem in python

### PR DESCRIPTION
**Pull request by natebru**
Let me know if I followed all the instructions. Feel free to add any feedback . Thanks

### CODE REVIEW

**Comment by thomasrayner** [comment]
Nice and consice. How does it compare to the other python solutions on leetcode?

(Chris and Glenn, Nate is somebody I work with 😁 )

**Comment by natebru** [comment]
image

ha pretty non-optimized, it is concise and clear as you mentioned but definitely has some opportunity to refactor/improve performance

**Comment by ChrisLGardner** [comment]
Pretty straightforward and readable solution there, looks good.

**Comment by thomasrayner** [comment]
That is such a weird distribution on that graph.

**Pull request merged**
